# Terraform Validation Template - Core CI validation steps
steps:
- task: TerraformTaskV4@4
  displayName: 'Terraform Format Check'
  inputs:
    provider: 'azurerm'
    command: 'fmt'
    workingDirectory: '$(System.DefaultWorkingDirectory)/infra'
    commandOptions: '-check -recursive'

- task: TerraformTaskV4@4
  displayName: 'Terraform Validate'
  inputs:
    provider: 'azurerm'
    command: 'validate'
    workingDirectory: '$(System.DefaultWorkingDirectory)/infra/envs/dev'

- task: TerraformTaskV4@4
  displayName: 'Terraform Init (no backend)'
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/infra/envs/dev'
    commandOptions: '-backend=false'

- task: TerraformTaskV4@4
  displayName: 'Terraform Plan'
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/infra/envs/dev'
    commandOptions: '-out=plan.out'

- task: Bash@3
  displayName: 'Security Scan with Checkov'
  inputs:
    targetType: 'inline'
    script: |
      pip install checkov
      checkov -d infra/ --framework terraform --output cli --quiet
    workingDirectory: '$(System.DefaultWorkingDirectory)'