name: Terraform Validation

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'infra/**'
      - '.github/workflows/terraform.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'infra/**'

jobs:
  validate:
    name: Validate Infrastructure
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.6
        
    - name: Terraform Format Check
      run: terraform fmt -check -recursive
      working-directory: infra
      
    - name: Terraform Init (no backend)
      run: terraform init -backend=false
      working-directory: infra/envs/dev
      
    - name: Terraform Validate
      run: terraform validate
      working-directory: infra/envs/dev
      
    - name: Security Scan with Checkov
      run: |
        pip install checkov
        checkov -d infra/ --framework terraform --output cli --quiet