name: Terraform Validation

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'infra/**'
      - '.github/workflows/terraform.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'infra/**'

jobs:
  validate:
    name: Validate Infrastructure
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Debug - List directory structure
      run: |
        pwd
        ls -la
        ls -la infra/ || echo "infra directory not found"
        
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.6
        
    - name: Terraform Format Check
      run: |
        cd infra
        terraform fmt -check -recursive
      
    - name: Terraform Init (no backend)
      run: |
        cd infra/envs/dev
        terraform init -backend=false
      
    - name: Terraform Validate
      run: |
        cd infra/envs/dev
        terraform validate
      
    - name: Security Scan with Checkov
      run: |
        pip install checkov
        checkov -d infra/ --framework terraform --output cli --quiet